apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-username
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      # restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
